spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hifz_app
    username: hifzapp
    password: hifzapp
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
app:
  jwtSecret: 512-bit super sekrit development key. Actually, it needs a bit more stuff to be 512 bits. This should do it.
  jwtExpirationMs: 3600000 # an hour